name: Accion de prueba
on:
    pull_request:
        branches:
            -master

jobs:
    deploy:
        name: Deploy Accion de prueba
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
